name: dart_leetcode
description: My leetcode in dart
version: 1.0.0
repository: https://github.com/hitchcliff/leetcode_dart.git
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
